from __future__ import annotations
import asyncio
import hashlib
import logging
import time
from PyQt6.QtWidgets import QWidget
from db.repository import AppRepository

logger = logging.getLogger(__name__)

_LOGIN_URL = "https://music.youtube.com"
_ORIGIN = "https://music.youtube.com"

# ytmusicapi 1.12+ requires __Secure-3PAPISID in the Cookie to generate SAPISIDHASH.
# We trigger auto-close when any of these appear in captured cookies.
_AUTH_COOKIES = {"__Secure-3PAPISID", "SAPISID", "__Secure-1PAPISID"}

_USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)


def _make_sapisidhash(sapisid: str) -> str:
    """Generate an Authorization: SAPISIDHASH header value.

    ytmusicapi uses this to identify browser-based auth (vs OAuth).
    A fresh hash is regenerated by ytmusicapi on every API request;
    the value stored here is only used for auth-type detection.
    """
    unix_ts = str(int(time.time()))
    h = hashlib.sha1(f"{unix_ts} {sapisid} {_ORIGIN}".encode()).hexdigest()
    return f"SAPISIDHASH {unix_ts}_{h}"


class YTMusicAuth:
    """Manages YouTube Music login via WebView cookie capture."""

    def __init__(self, repo: AppRepository) -> None:
        self._repo = repo

    async def load_auth(self) -> dict[str, str] | None:
        return await self._repo.load_credential("ytmusic")

    async def login(self, parent: QWidget | None = None) -> dict[str, str] | None:
        from ui.components.login_dialog import LoginDialog  # lazy: needs WebEngine

        loop = asyncio.get_event_loop()
        future: asyncio.Future[dict[str, str] | None] = loop.create_future()

        dialog = LoginDialog(
            url=_LOGIN_URL,
            target_cookies=list(_AUTH_COOKIES),  # auto-close when any auth cookie seen
            title="YouTube Music — 登录",
            capture_all_cookies=True,
            show_done_button=True,
            parent=parent,
        )

        def _on_captured(cookies: dict) -> None:
            if not future.done():
                future.set_result(cookies)

        def _on_rejected() -> None:
            if not future.done():
                future.set_result(None)

        dialog.cookies_captured.connect(_on_captured)
        dialog.rejected.connect(_on_rejected)
        dialog.show()

        cookies = await future
        if not cookies:
            logger.debug("YTMusic login cancelled — no cookies captured")
            return None

        auth_present = _AUTH_COOKIES & cookies.keys()
        if not auth_present:
            logger.warning(
                "YTMusic: no auth cookie found. Captured keys: %s",
                list(cookies.keys())[:10],
            )
        else:
            logger.info("YTMusic: found auth cookies: %s", auth_present)

        headers = self._build_headers(cookies)
        await self._repo.save_credential("ytmusic", headers)
        logger.info("YTMusic credentials saved (%d cookies captured)", len(cookies))
        return headers

    async def ensure_authenticated(
        self, parent: QWidget | None = None
    ) -> dict[str, str] | None:
        existing = await self.load_auth()
        if existing and existing.get("Cookie"):
            return existing
        return await self.login(parent)

    @staticmethod
    def _build_headers(cookies: dict[str, str]) -> dict[str, str]:
        """Build a ytmusicapi 1.12-compatible headers dict.

        Critical: ytmusicapi 1.12+ determines auth type from the Authorization
        header.  Without 'SAPISIDHASH' in Authorization it defaults to OAuth and
        raises an error.  We pre-compute a SAPISIDHASH here; ytmusicapi will
        re-generate a fresh one on every API request using the stored sapisid.
        """
        cookie_str = "; ".join(f"{k}={v}" for k, v in cookies.items())

        # ytmusicapi.sapisid_from_cookie() reads __Secure-3PAPISID from the cookie
        sapisid = (
            cookies.get("__Secure-3PAPISID")
            or cookies.get("SAPISID")
            or ""
        )

        return {
            "User-Agent": _USER_AGENT,
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.5",
            "Content-Type": "application/json",
            "Authorization": _make_sapisidhash(sapisid),   # ← required for BROWSER detection
            "X-Goog-AuthUser": "0",
            "x-origin": _ORIGIN,
            "Cookie": cookie_str,
        }
